#!/bin/bash

options=(
    style=round
    width=3.0
    active_color=0xfff8f8f8
	inactive_color=0xc02c2e34
	background_color=0x302c2e34
    order=above
    blacklist="firefox,League of Legends"
)

borders "${options[@]}"
